lv_input:
  - { lv: auditVol,   size: 4.4 }
  - { lv: homeVol,    size: 13 }
  - { lv: logVol,     size: 2 }
  - { lv: rootVol,    size: 11 }
  - { lv: swapVol,    size: 2 }
  - { lv: varTmpVol,  size: 2 }
  - { lv: varVol,     size: 6 }

